"""
DNS Module - on_disable Hook

Executed when the module is deactivated:
1. Stop and disable bind9 service
2. Remove firewall rules
3. Reset named.conf.local to empty

Does NOT remove:
- /etc/bind/ directory
- Zone files
- apt packages
"""
import subprocess
import logging
from pathlib import Path

logger = logging.getLogger(__name__)


def run():
    """on_disable hook for DNS module."""
    logger.info("Running DNS on_disable hook")

    # 1. Stop and disable named
    for svc in ["named", "bind9"]:
        try:
            subprocess.run(
                ["systemctl", "stop", svc],
                capture_output=True, text=True, timeout=15
            )
        except Exception:
            pass

        try:
            subprocess.run(
                ["systemctl", "disable", svc],
                capture_output=True, text=True
            )
        except Exception:
            pass

    logger.info("bind9/named stopped and disabled")

    # 2. Remove firewall rules using core iptables
    try:
        from core.firewall import iptables as core_iptables
        core_iptables.remove_jump_rule("INPUT", "MOD_DNS_INPUT", "filter")
        core_iptables.flush_chain("MOD_DNS_INPUT", "filter")
        core_iptables.delete_chain("MOD_DNS_INPUT", "filter")
        logger.info("DNS firewall rules removed")
    except Exception as e:
        logger.warning(f"Error removing firewall rules: {e}")

    # 3. Reset named.conf.local
    local_conf = Path("/etc/bind/named.conf.local")
    try:
        local_conf.write_text(
            "// BIND9 Local Zones - generated by MADMIN DNS Module\n"
            "// Module disabled. No zones configured.\n"
        )
        logger.info(f"Reset {local_conf} to initial state")
    except Exception as e:
        logger.warning(f"Failed to reset config: {e}")

    logger.info("DNS on_disable complete")
    return True
