"""
DNS Module - Post-install Hook

Executes after module installation to configure system for bind9:
1. Create /etc/bind/zones directory
2. Stop any running bind9 to avoid conflicts
3. Write initial empty config
4. Add 'named' to SystemdService whitelist
"""
import subprocess
import logging
from pathlib import Path

logger = logging.getLogger(__name__)


def run():
    """
    Post-installation system configuration for DNS.

    This hook is executed after:
    - apt packages are installed (bind9, bind9-utils, dnsutils)
    - Database migrations are complete
    """
    logger.info("Running DNS post-install hook...")
    errors = []

    # 1. Create zones directory
    zones_dir = Path("/etc/bind/zones")
    try:
        zones_dir.mkdir(parents=True, exist_ok=True)
        logger.info(f"Ensured {zones_dir} exists")
    except PermissionError:
        errors.append(f"Permission denied creating {zones_dir}")
    except Exception as e:
        errors.append(f"Failed to create {zones_dir}: {e}")

    # 2. Stop and disable bind9 (MADMIN manages the lifecycle)
    for svc in ["named", "bind9"]:
        try:
            subprocess.run(
                ["systemctl", "stop", svc],
                capture_output=True, text=True, timeout=15
            )
            subprocess.run(
                ["systemctl", "disable", svc],
                capture_output=True, text=True, timeout=15
            )
        except Exception:
            pass
    logger.info("Stopped and disabled bind9/named (MADMIN will manage the service)")

    # 3. Add 'named' to SystemdService whitelist
    try:
        from core.services.service import SystemdService
        svc_name = "named.service"
        if svc_name not in SystemdService.ALLOWED_SERVICES:
            SystemdService.ALLOWED_SERVICES.append(svc_name)
            logger.info(f"Added {svc_name} to SystemdService whitelist")
    except Exception as e:
        errors.append(f"Failed to update service whitelist: {e}")

    # 4. Write initial named.conf.local (empty)
    local_conf = Path("/etc/bind/named.conf.local")
    try:
        local_conf.write_text(
            "// BIND9 Local Zones - generated by MADMIN DNS Module\n"
            "// No zones configured yet.\n"
        )
        logger.info(f"Wrote initial config to {local_conf}")
    except PermissionError:
        errors.append(f"Permission denied writing to {local_conf}")
    except Exception as e:
        errors.append(f"Failed to write initial config: {e}")

    # Report results
    if errors:
        for err in errors:
            logger.error(f"Post-install error: {err}")
        logger.warning("DNS post-install completed with warnings")
    else:
        logger.info("DNS post-install completed successfully")

    return True
